# Generated by Django 4.2.3 on 2023-07-24 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('current_floor', models.PositiveIntegerField(default=1)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'elevator',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.PositiveIntegerField()),
                ('is_upward', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
            options={
                'db_table': 'elevator_request',
                'ordering': ['-created_on'],
            },
        ),
    ]
