# Generated by Django 4.2.3 on 2023-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='is_moving',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='is_working',
        ),
        migrations.RemoveField(
            model_name='elevatorrequest',
            name='is_upward',
        ),
        migrations.AddField(
            model_name='elevator',
            name='direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('idle', 'Idle')], default='idle', max_length=10),
        ),
        migrations.AddField(
            model_name='elevator',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('maintenance', 'Maintenance')], default='working', max_length=15),
        ),
        migrations.AddField(
            model_name='elevatorrequest',
            name='requested_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=10),
        ),
    ]
