# Generated by Django 4.2.3 on 2023-07-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_remove_elevator_is_moving_remove_elevator_is_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorrequest',
            name='total_floors',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
