# Generated by Django 4.2.3 on 2023-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_remove_elevatorrequest_total_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='door_open',
            field=models.BooleanField(default=False),
        ),
    ]
